[package]
name = "passutil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libshadow = { path = "../libshadow" }
clap = { version = "3.1.9", features = ["derive"] }
anyhow = "1.0.56"